# Ansible playbook practice from scratch.
# Author: Shashidhar
# Date: 20/Aug/2024

---

- name: Install and Start the service
  hosts: localhost
  become: yes

  tasks:
  - name: Installing nginx
    apt:
      name: nginx
      state: present
  - name: Starting the nginx service
    service:
      name: nginx
      state: started
      enabled: true
