# Ansible playbook practice from scratch.
# Author: Shashidhar
# Date: 20/Aug/2024
---
- name: Playbook
  hosts: localhost
  tasks:
  - name: Test Connectivity
    ping:
  - name: "Print Output"
    debug: msg="Message is correct"